
* 1: Button press (hall)
1. Send melding fra io driver opp til et høyere nivå.
    - Hvis lys allerede er tent, ignorer button press.
2. Registrere button press lokalt, skru på lys på panel (start timeout).
3. Broadcaste at man fikk et button press. (Tidsrom på 1s)
    Den som fikk ordren sender melding som inneholder:
    - Ordren (hvilken etasje ordren kom fra, retning)
    Alle som mottar ordren sender melding tilbake som inneholder:
    - Ordren det gjelder.
    - Etasje denne heisen er i, er retning (evt stillestående)
    - (Trenger å vite IP adressen fra heisen, enten legge til IP i melding, eller hente det ut fra UDP broadcast melding)
4. Den som sendte ut ordren beregner avstander for alle heiser. 
    prioritet:
    - stillestående uten ordre
    - Nærme etasjen ordren kom fra, og beveger seg i riktig retning.
    - Feil retning - avstanden regnes ut ved at heisen må bevege seg helt til enden (helt opp/helt ned) og deretter gå til etasjen orderen kom fra.
5. Bestem hvem som skal ta ordren basert på avstand.
    - Dette vil fungere bra også uten nettverksforbindelse, siden da vil eneste heis som kan behandle ordren være heisen som fikk ordren.
6. Broadcaste hvem som skal ta ordren.
    Melding inneholder:
    - Ordre
    - Hvem som tar den (IP addressen til den som skal ta den).

    Tidsrom på 1s:
        - Venter på ACK på ordre mottat (Ordre behandlet).
        - Hvis ikke mottar ACK innen tidsrommet:
            - Broadcaste samme ordre til den heisen som er nest nærmest. (Gå til steg 6). Hvis den du skal broadcaste til er deg selv, ikke broadcastast, men gå til "behandle ordre selv".
        - Hvis sendt ordre til alle og ikke mottatt ACK, behandle orden selv (behandle ordre selv) (Ordre behandlet)


* 2. Mottar netverkspakke med ordre
1. Hvis man mottar ordre fra nettverksmodul
    - Hvis kvittering:
        - Skru av lys
    - Hvis ny ordre
        - Send melding til IO modul om hvilket lys som skal skrus på (start timeout).
        - Broadcast ordren, posisjon, retning og IP.


* 3. Cab call button press
1. Send ny ordre til kø modul

* 4. Ankommer etasje
1. Åpne dør og start dørtimer.
2. Skru av lys (cab call og hall call i riktig retning).
3. Hvis hall call:
    - Kvitter ordre ved å broadcaste ordre og 'done'.
4. Send melding til kø om å slette ordre (som ligger fremst i køen).


* Lys Modul
- Hvis IO modul detekterer at man er i en ny etasje, sett på riktig lys og gi beskjed om ny etasje til høyere nivå.

- Hvis hall lys timeout - Antar at ordren aldri ble betjent, gå til case 1, step 2. (Sannsynlighet for at to heiser har timeout samtidig er veldig liten.)


* Motor driver
- Passer på at man IKKE beveger motor hvis dør er åpen.
- Teste om motoren beveger seg riktig, basert på timeout. Kalibrer timeout ved oppstart av sytemet

* Process killed
1. Ha et watchdog program som skjekker om go programmet svarer (ved å sendre sin PID i en pipe).
2. Hvis ikke, kill PID og start programmet på nytt.

* Kø liste modul
Kø (linked list) for ordre (sortert etter kost):
- Kø "modulen" regner ut kostnad (sender inn ordre, får ut ordre).
- Hvis du sette ny ordre i kø:
    - Gå gjennom lista og skjekk om kostnad på ny ordre er lavere enn element. Hvis ja, plasser ny ordre før denne ordren.
    - Hvis ingen element har høyere kost, plasser ny ordre sist.
- Hvis ny ordre er nærmere enn forrige nærmeste ordre.
    - Endre hvilken etasje man skal gå til.