* Q/A session
** Figures
- Only need hand-drawn figures
** Network
- UDP broadcast good
- Smart with ACK/protocol for handling packet loss/ node offline etc. (Mostly for important messages)
** Acceptance test
- Previous years, students have not implemented this
- Project not so big that we /need/ it
** Send all elevators to same floor (worst case)
- Okey, not okay to stop at every floor "just to be sure"
** Timers
- Timers are *good*
- Timestamp order in order table and periodically check it. Easier than one timer thread per order.
- Could be implemented as one thread that periodically checks the timestamp of incomplete orders and signals if order is not completed within a given time period.
** In the case of a restart
- You could receive an answer to a message that you haven't sent yet. (You could send a message, then restart, then receive the answer to the sent message. This could cause confusion and become a problem.)
** Hall lights
- Okey to not turn on hall lights if network packet loss, otherwise not okey
** Presentation
- Keep it simple
- Clear to us - clear to them
** Modularizing
- Good if modules doesn't need complete (all information) to take decisions. 
